spring:
  application:
    name: quarry
  profiles:
    active: common
server:
  port: 8081
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false